### PR TITLE
Tool implementation section

### PR DESCRIPTION
**Pull request by allegroCoder**
#3 

Tool implementation section nearly written from scratch. All the benchmarks from `graph families` repository have been added and discussed.

### CODE REVIEW

**Comment by allegroCoder** [comment]
I still need to give this section a good proof-read and think of any possible improvement.

**Comment by allegroCoder** [comment]
@snowleopard : could you read this section and let me know your comments, please?

I have put a `TODO` in the middle. Could you suggest me a paper to read, so that for me to describe the process-mining benchmarks?

**Comment by snowleopard** [comment]
@allegroCoder I'm currently very busy on business travel. Let me come back to your paper next week. Please do the merge and keep working on the paper in the meanwhile.

**Comment by allegroCoder** [comment]
No worries @snowleopard. Thanks for letting me know!

**Pull request merged**
